accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'


urlpatterns = [
    path('signup/',views.signUpView,name='signup'),
    path('login/',views.loginView,name='login'),
    path('logout/',views.logoutView,name='logout')

]

article/urls.py
from django.urls import path
from . import views

app_name='article'

urlpatterns = [
    path('',views.ArticleView.as_view(),name='articlelist'),

    path('create_article/',views.createArticleView,name='create_article'),

    path('<slug:slug>/',views.articleDetails,name='detail')

]

main_app/urls.py
from django.urls import path
from .import views
from article import views as arview

urlpatterns = [
    path('',arview.ArticleView.as_view(),name='home'),
    path('about/',views.AboutView.as_view(),name='about')

]

newproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main_app.urls')),
    path('article/',include('article.urls')),
    path('accounts/',include('accounts.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

article/models.py
from django.db import models
from django.contrib.auth.models import User

class Article(models.Model):
    title   = models.CharField(max_length=100) 
    slug    = models.SlugField(default='')
    body    = models.TextField(blank=False) 
    date    = models.DateTimeField(auto_now_add=True)
    thumb   = models.ImageField(default='dafalut.png',blank=True)
    author    = models.ForeignKey(User,default=None,on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
    def snippet(self):
        return self.body[:50] + "..."

main_app/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from . import models

class CreateArticleform(forms.ModelForm):
    class Meta:
        model=models.Article
        fields = ['title','body','slug','thumb']

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout


def signUpView(request):

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('article:articlelist')
    else:
        form=UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})


def loginView(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user=form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('article:articlelist')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{ 'form':form })

def logoutView(request):
    if request.method == 'POST':
        logout(request)
        return redirect('article:articlelist')
        

article/views.py
from django.views.generic import ListView
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .models import Article
from django.contrib.auth.decorators import login_required
from .import forms



class ArticleView(ListView):
    template_name='article/home.html'

    model=Article

    def get_queryset(self):
        queryset=super().get_queryset

        return queryset

def articleDetails(request,slug):

    articles=Article.objects.get(slug=slug)

    return render(request,'article/article_details.html',{'article_detail': articles })
    

@login_required(login_url ="/accounts/login")
def createArticleView(request):
    if request.method=='POST':
        form = forms.CreateArticleform(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect ('article:articlelist')
    else:
        form=forms.CreateArticleform()
    return render(request,'article/create_article.html',{'form':form})

main_app/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name='main_app/index.html'

class AboutView(TemplateView):
    template_name='main_app/about.html'

templates/accounts/login.html
{% extends 'main_app/base.html' %}

{% block body %}
<div class="container">
    <h4 class="display-5 text-center">Login page</h4>
 
    <form action="{% url 'accounts:login' %}" method="POST">
    
    {% csrf_token %}   
    {{ form }}

    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    
    <input type="submit" value="Submit">
    
    </form>

</div>
{% endblock %}

templates/accounts/signup.html
{% extends 'main_app/base.html' %}

{% block body %}
<div class="container">
    <h4 class="display-5 text-center">SignUp page</h4>
 
    <form action="{% url 'accounts:signup' %}" method="POST">
    
     {% csrf_token %}   
    {{ form }}
    
    <input type="submit" value="Submit">
    
    </form>

</div>
{% endblock %}

templates/article/article_details.html
{% extends 'main_app/base.html' %}

{% block body %}

<div class="container">
    <div class="jumbotron">
        <h3 class="display-5 text-center">{{ article_detai.title }}</h3>
        <img src="{{article_detail.thumb.url}}"
        <h5 class="display-5">{{ article_detail.date }}</h5>
        <p class="lear">{{ article_detail.body }}</p>
    </div>
</div>

{% endblock %}

templates/article/create_article.html
{% extends 'main_app/base.html' %}

{% block body %}
<div class="container">
    <h4 class="display-5 text-center">Create Article Page</h4>
    <form action="{% url 'article:create_article' %}" method="post" enctype="multipart/form-data">
    
        {% csrf_token %}

        {{ form }}

        <input type="submit" value="Create">
    
    </form>

</div>
{% endblock %}

templates/article/home.html
{% extends 'main_app/base.html' %}

{% block body %}

<div class="container">
    <div class="jumbotron">
        {% for article in object_list %}
        <h3 class="display-4 text-center"><a href="{% url 'article:detail' slug=article.slug %}">{{ article.title }}</a></h4>
        <h5 class="display-5">{{ article.date }}</h5>
        <p class="lear">{{ article.snippet }}</p>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/main_app/about.html
{% extends 'main_app/base.html' %}

{% block body %}

<div class="container">
    <div class="jumbotron">
        <h4 class="display-3 text-center">About page</h4>
    </div>
</div>

{% endblock %}

templates/main_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Article site</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
       

    <nav>
        <ul>
            {% if user.is_authenticated  %}
            <li>
                <form action="{% url 'accounts:logout' %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-primary" type="submit">Logout</button>
                </form>
            </li>
            <li>
                <a href="{% url 'article:create_article' %}">New Article</a>
            </li>
            {% else %}
            <li><a href="{% url 'accounts:signup' %}" class="btn btn-praimary">Sign Up</a></li>
            <li><a href="{% url 'accounts:login' %}" class="btn btn-praimary">Login</a></li>

            {% endif %}
        </ul>
    </nav>

    {% block body %}

    {% endblock %}
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

templates/main_app/index.html
{% extends 'main_app/base.html' %}

{% block body %}

<div class="container">
    <div class="jumbotron">
        <h4 class="display-3 text-center">Home page</h4>
    </div>
</div>

{% endblock %}